jenkins:
  systemMessage: "Seeder job"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
jobs:
  - script: >
      multibranchPipelineJob('temperature-watcher') {
        branchSources {
                git {
                id = 'temperature-watcher'
                remote('ssh://git@infra_git_1:22/dmytro/temperature-watcher.git')
                credentialsId('gitea')
                    }
                      }
                                                    }
