jenkins:
  systemMessage: "Seeder Job"
jobs:
  - script: >
        multibranchPipelineJob('temperature-watcher') {
        branchSources {
                git {
                id = 'temperature-watcher'
                remote('ssh://git@openmediavault.local:222/dmytro/temperature-watcher.git')
                }
      }
}